"use client";

import { useEffect, useState } from "react";
import type { TechJob } from "@/components/TechnicianWorkspace";
import { flushJobOutbox, queueJobAction, readOutbox } from "@/lib/offline-outbox";

export default function OfflineWorkspace() {
  const [jobs,setJobs] = useState<TechJob[]>([]); const [savedAt,setSavedAt] = useState<string | null>(null); const [pending,setPending] = useState(0); const [he,setHe] = useState(false);
  useEffect(() => { const load = window.setTimeout(() => { setHe(document.documentElement.dir === "rtl" || navigator.language.startsWith("he")); try { const snapshot = JSON.parse(localStorage.getItem("servicepro:tech-snapshot") ?? "{}"); setJobs(Array.isArray(snapshot.jobs) ? snapshot.jobs : []); setSavedAt(typeof snapshot.savedAt === "string" ? snapshot.savedAt : null); } catch {} setPending(readOutbox().length); },0); const sync = async () => { const result = await flushJobOutbox(); setPending(result.pending); if (result.sent) location.href = "/tech"; }; window.addEventListener("online", sync); if (navigator.onLine) sync(); return () => { window.clearTimeout(load); window.removeEventListener("online", sync); }; }, []);
  function queue(jobId: string, action: "start" | "complete") { setPending(queueJobAction(jobId,action)); setJobs((rows) => rows.map((job) => job.id === jobId ? { ...job, status: action === "start" ? "in_progress" : "done" } : job)); }
  return <main className="offline-page"><div><span className="offline-mark">SP</span><h1>{he ? "עובדים בלי חיבור" : "Working offline"}</h1><p>{he ? "אפשר להתחיל או להשלים עבודות. השינויים יישלחו אוטומטית כשהחיבור יחזור." : "You can start or complete jobs. Changes will send automatically when the connection returns."}</p>{pending > 0 && <div className="offline-pending">{pending} {he ? "עדכונים ממתינים לסנכרון" : "updates waiting to sync"}</div>}{savedAt && <small>{he ? "נשמר לאחרונה" : "Last saved"}: {new Intl.DateTimeFormat(he ? "he-IL" : "en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(savedAt))}</small>}<div className="offline-jobs">{jobs.map((job) => <article key={job.id}><div><strong>{job.service}</strong><small>{job.customers?.name} · {(job.start_time ?? "").slice(0,5)}</small></div><span>{job.status.replaceAll("_"," ")}</span><footer><button type="button" onClick={() => queue(job.id,"start")}>{he ? "התחלה" : "Start"}</button><button type="button" onClick={() => queue(job.id,"complete")}>{he ? "סיום" : "Complete"}</button></footer></article>)}</div>{jobs.length === 0 && <p>{he ? "פתחו פעם אחת את יום העבודה כשהמכשיר מחובר כדי לשמור את השיבוצים." : "Open My workday once while online to save assignments on this device."}</p>}<a href="/tech">{he ? "ניסיון להתחבר מחדש" : "Try to reconnect"}</a></div></main>;
}
