export type CatalogPackItem = { key: string; en: string; he: string; kind: "service" | "part" };
export type IndustryPack = { key: string; en: string; he: string; items: CatalogPackItem[] };

const s = (key: string, en: string, he: string): CatalogPackItem => ({ key, en, he, kind: "service" });
const p = (key: string, en: string, he: string): CatalogPackItem => ({ key, en, he, kind: "part" });

export const INDUSTRY_PACKS: IndustryPack[] = [
  { key: "air-duct", en: "Air duct cleaning", he: "ניקוי תעלות מיזוג", items: [
    s("inspection", "Air duct system inspection", "בדיקת מערכת תעלות המיזוג"), s("whole-home", "Whole-home air duct cleaning", "ניקוי תעלות מיזוג לכל הבית"),
    s("per-vent", "Additional supply or return vent", "פתח אספקה או חזרה נוסף"), s("return", "Return-air duct cleaning", "ניקוי תעלות אוויר חוזר"),
    s("sanitizing", "Air duct sanitizing treatment", "חיטוי תעלות המיזוג"), s("deodorizing", "Odor-neutralizing treatment", "טיפול לנטרול ריחות"),
    s("mold", "Suspected microbial growth treatment", "טיפול בחשד להתפתחות עובש"), s("blower", "Blower compartment cleaning", "ניקוי תא המפוח"),
    s("coil", "Evaporator coil cleaning", "ניקוי סוללת המאייד"), s("register", "Vent register cleaning", "ניקוי תריסי האוורור"),
    s("seal", "Accessible duct leak sealing", "איטום דליפות נגישות בתעלות"), s("repair", "Flexible duct repair", "תיקון תעלה גמישה"),
    s("replace", "Flexible duct replacement", "החלפת תעלה גמישה"), s("install", "New duct run installation", "התקנת קו תעלה חדש"),
    p("flex-duct", "Insulated flexible duct", "תעלה גמישה מבודדת"), p("register-part", "Supply register", "תריס אספקת אוויר"),
    p("return-grille", "Return-air grille", "גריל אוויר חוזר"), p("mastic", "Duct sealing mastic", "חומר איטום לתעלות"), p("filter", "HVAC air filter", "מסנן אוויר למיזוג"),
  ]},
  { key: "dryer-vent", en: "Dryer vent cleaning", he: "ניקוי פתח מייבש", items: [
    s("inspection", "Dryer vent safety inspection", "בדיקת בטיחות לפתח המייבש"), s("clean", "Dryer vent cleaning", "ניקוי צינור המייבש"),
    s("roof", "Roof-exit dryer vent cleaning", "ניקוי פתח מייבש היוצא דרך הגג"), s("long-run", "Long-run dryer vent cleaning", "ניקוי קו מייבש ארוך"),
    s("bird-nest", "Bird-nest removal", "פינוי קן ציפורים"), s("lint", "Heavy lint blockage removal", "פינוי סתימת מוך כבדה"),
    s("disconnect", "Dryer disconnect and reconnect", "ניתוק וחיבור מחדש של המייבש"), s("transition", "Transition hose replacement", "החלפת צינור החיבור למייבש"),
    s("repair", "Dryer vent line repair", "תיקון קו האוורור של המייבש"), s("reroute", "Dryer vent rerouting", "שינוי תוואי צינור המייבש"),
    s("install", "New dryer vent installation", "התקנת קו מייבש חדש"), s("booster", "Dryer booster fan service", "שירות למאוורר עזר למייבש"),
    s("multi-unit", "Multi-unit dryer vent cleaning", "ניקוי פתחי מייבש בבניין רב-יחידות"), s("airflow", "Before-and-after airflow test", "בדיקת זרימת אוויר לפני ואחרי"),
    p("transition-part", "UL-listed transition duct", "צינור חיבור תקני למייבש"), p("wall-cap", "Exterior dryer vent hood", "כיסוי חיצוני לפתח מייבש"),
    p("roof-cap", "Dryer roof vent cap", "כובע גג לפתח מייבש"), p("clamp", "Vent clamp", "חבק לצינור אוורור"), p("booster-part", "Dryer booster fan", "מאוורר עזר למייבש"),
  ]},
  { key: "chimney", en: "Chimney service", he: "שירותי ארובות", items: [
    s("sweep", "Standard chimney sweep", "ניקוי ארובה רגיל"), s("inspect-1", "Level 1 chimney inspection", "בדיקת ארובה דרגה 1"),
    s("inspect-2", "Level 2 camera inspection", "בדיקת מצלמה לארובה דרגה 2"), s("creosote", "Heavy creosote removal", "הסרת קריאוזוט כבד"),
    s("glaze", "Glazed creosote treatment", "טיפול בקריאוזוט מזוגג"), s("animal", "Animal or nest removal", "פינוי בעל חיים או קן"),
    s("cap-install", "Chimney cap installation", "התקנת כובע ארובה"), s("crown-repair", "Chimney crown repair", "תיקון כתר הארובה"),
    s("crown-rebuild", "Chimney crown rebuild", "בנייה מחדש של כתר הארובה"), s("waterproof", "Chimney waterproofing", "איטום ארובה נגד מים"),
    s("tuckpoint", "Mortar joint tuckpointing", "חידוש מישקי טיט בארובה"), s("brick", "Chimney brick replacement", "החלפת לבנים בארובה"),
    s("flashing", "Chimney flashing repair", "תיקון פח האיטום סביב הארובה"), s("liner-repair", "Chimney liner repair", "תיקון ציפוי הארובה"),
    s("liner-install", "Stainless-steel liner installation", "התקנת שרוול נירוסטה לארובה"), s("firebox", "Firebox repair", "תיקון תא הבעירה"),
    p("cap", "Stainless-steel chimney cap", "כובע ארובה מנירוסטה"), p("liner", "Stainless-steel chimney liner", "שרוול ארובה מנירוסטה"),
    p("damper", "Top-sealing damper", "דמפר עליון אוטם"), p("crown-seal", "Crown seal coating", "ציפוי איטום לכתר"), p("firebrick", "Firebrick", "לבנת שמוט"),
  ]},
  { key: "painting", en: "Painting", he: "צביעה", items: [
    s("consult", "Color and project consultation", "ייעוץ צבע ותכנון העבודה"), s("interior-room", "Interior room painting", "צביעת חדר פנימי"),
    s("interior-home", "Whole-home interior painting", "צביעת פנים לכל הבית"), s("ceiling", "Ceiling painting", "צביעת תקרה"),
    s("trim", "Trim and baseboard painting", "צביעת פאנלים וגימורים"), s("door", "Door painting", "צביעת דלת"),
    s("cabinet", "Cabinet refinishing", "חידוש וצביעת ארונות"), s("exterior", "Exterior house painting", "צביעת חוץ לבית"),
    s("siding", "Siding painting", "צביעת חיפוי חוץ"), s("fence", "Fence or deck staining", "צביעה או גיוון של גדר ודק"),
    s("pressure-wash", "Pre-paint pressure washing", "שטיפה בלחץ לפני צביעה"), s("drywall", "Drywall patch and texture repair", "תיקון גבס וטקסטורה"),
    s("wallpaper", "Wallpaper removal", "הסרת טפט"), s("lead", "Lead-safe surface preparation", "הכנת משטח בטוחה לצבע עופרת"),
    p("paint", "Interior or exterior paint", "צבע פנים או חוץ"), p("primer", "Bonding primer", "צבע יסוד מקשר"), p("caulk", "Painter's caulk", "חומר איטום לצביעה"),
    p("patch", "Wall patch compound", "חומר תיקון לקיר"), p("plastic", "Floor and furniture protection", "כיסוי להגנת רצפה ורהיטים"),
  ]},
  { key: "masonry", en: "Masonry", he: "עבודות אבן ולבנים", items: [
    s("inspect", "Masonry condition inspection", "בדיקת מצב עבודות האבן והלבנים"), s("tuckpoint", "Brick tuckpointing", "חידוש מישקים בקיר לבנים"),
    s("brick-repair", "Brick wall repair", "תיקון קיר לבנים"), s("brick-replace", "Individual brick replacement", "החלפת לבנה בודדת"),
    s("stone-repair", "Stone veneer repair", "תיקון חיפוי אבן"), s("block", "Concrete-block repair", "תיקון בלוק בטון"),
    s("step", "Masonry step repair", "תיקון מדרגות בנייה"), s("walkway", "Brick or stone walkway repair", "תיקון שביל אבן או לבנים"),
    s("wall", "Retaining wall repair", "תיקון קיר תמך"), s("mailbox", "Masonry mailbox repair", "תיקון תיבת דואר בנויה"),
    s("clean", "Masonry cleaning", "ניקוי אבן ולבנים"), s("seal", "Masonry water-repellent treatment", "טיפול דוחה מים לאבן ולבנים"),
    s("crack", "Mortar crack repair", "תיקון סדקים בטיט"), s("new", "Small masonry installation", "עבודת בנייה קטנה חדשה"),
    p("brick", "Matching brick", "לבנה תואמת"), p("mortar", "Type N/S mortar", "טיט מסוג N או S"), p("stone", "Matching stone veneer", "אבן חיפוי תואמת"),
    p("flashing", "Masonry flashing", "פח איטום לבנייה"), p("sealant", "Masonry sealant", "חומר איטום לאבן ולבנים"),
  ]},
  { key: "siding", en: "Siding", he: "חיפוי חוץ", items: [
    s("inspect", "Siding inspection", "בדיקת חיפוי החוץ"), s("vinyl-repair", "Vinyl siding repair", "תיקון חיפוי ויניל"),
    s("fiber-repair", "Fiber-cement siding repair", "תיקון חיפוי פייבר צמנט"), s("wood-repair", "Wood siding repair", "תיקון חיפוי עץ"),
    s("panel", "Siding panel replacement", "החלפת לוח חיפוי"), s("corner", "Outside-corner replacement", "החלפת פינת חיפוי חיצונית"),
    s("trim", "Exterior trim repair", "תיקון גימור חיצוני"), s("soffit", "Soffit repair", "תיקון סופיט"),
    s("fascia", "Fascia repair", "תיקון פס פאשיה"), s("housewrap", "House-wrap repair", "תיקון יריעת איטום הבית"),
    s("seal", "Siding joint sealing", "איטום חיבורי החיפוי"), s("wash", "Siding soft wash", "שטיפה עדינה של חיפוי החוץ"),
    s("install", "New siding installation", "התקנת חיפוי חוץ חדש"), s("storm", "Storm-damage siding repair", "תיקון נזקי סערה בחיפוי"),
    p("vinyl", "Vinyl siding panel", "לוח חיפוי ויניל"), p("fiber", "Fiber-cement siding board", "לוח חיפוי פייבר צמנט"), p("j-channel", "J-channel", "מסילת J"),
    p("corner", "Outside corner post", "עמוד פינה חיצונית"), p("wrap", "Weather-resistant house wrap", "יריעת איטום חיצונית"),
  ]},
  { key: "locksmith", en: "Locksmith", he: "מנעולנות", items: [
    s("lockout-home", "Residential lockout", "פריצת דלת לבית"), s("lockout-business", "Commercial lockout", "פריצת דלת לעסק"),
    s("lockout-auto", "Vehicle lockout", "פתיחת רכב נעול"), s("rekey", "Lock rekeying", "התאמת מפתח חדש למנעול"),
    s("lock-install", "New lock installation", "התקנת מנעול חדש"), s("deadbolt", "Deadbolt installation", "התקנת מנעול בריח"),
    s("smart", "Smart-lock installation", "התקנת מנעול חכם"), s("repair", "Lock repair", "תיקון מנעול"),
    s("key", "House-key duplication", "שכפול מפתח לבית"), s("master", "Master-key system setup", "הקמת מערכת מפתח מאסטר"),
    s("panic", "Panic-bar service", "שירות לידית בהלה"), s("closer", "Door-closer service", "שירות למחזר דלת"),
    s("safe", "Safe opening consultation", "ייעוץ לפתיחת כספת"), s("emergency", "After-hours emergency service", "שירות חירום מחוץ לשעות הפעילות"),
    p("deadbolt-part", "Deadbolt lock", "מנעול בריח"), p("smart-part", "Smart lock", "מנעול חכם"), p("cylinder", "Replacement lock cylinder", "צילינדר חלופי"),
    p("panic-part", "Panic exit device", "מתקן יציאת חירום"), p("closer-part", "Commercial door closer", "מחזר דלת מסחרי"),
  ]},
  { key: "garage-door", en: "Garage door", he: "דלתות מוסך", items: [
    s("inspect", "Garage-door safety inspection", "בדיקת בטיחות לדלת מוסך"), s("tune", "Garage-door tune-up", "טיפול תקופתי לדלת מוסך"),
    s("spring", "Broken spring replacement", "החלפת קפיץ שבור"), s("cable", "Lift cable replacement", "החלפת כבל הרמה"),
    s("roller", "Roller replacement", "החלפת גלגלים"), s("track", "Track alignment or repair", "יישור או תיקון מסילה"),
    s("panel", "Door panel replacement", "החלפת פנל בדלת"), s("seal", "Bottom weather seal replacement", "החלפת אטם תחתון"),
    s("opener-repair", "Garage-door opener repair", "תיקון מנוע לדלת מוסך"), s("opener-install", "Garage-door opener installation", "התקנת מנוע לדלת מוסך"),
    s("sensor", "Safety-sensor service", "שירות לחיישני בטיחות"), s("remote", "Remote or keypad programming", "תכנות שלט או לוח מקשים"),
    s("door-install", "New garage-door installation", "התקנת דלת מוסך חדשה"), s("emergency", "Emergency stuck-door service", "שירות חירום לדלת תקועה"),
    p("spring-part", "Torsion spring", "קפיץ פיתול"), p("cable-part", "Garage-door lift cable", "כבל הרמה לדלת מוסך"), p("roller-part", "Nylon roller", "גלגל ניילון"),
    p("seal-part", "Bottom weather seal", "אטם תחתון"), p("opener-part", "Garage-door opener", "מנוע לדלת מוסך"),
  ]},
  { key: "hvac", en: "HVAC", he: "מיזוג אוויר", items: [
    s("diagnostic", "HVAC diagnostic visit", "ביקור אבחון למערכת מיזוג"), s("maintenance", "Seasonal HVAC maintenance", "טיפול עונתי למערכת מיזוג"),
    s("ac-repair", "Air-conditioner repair", "תיקון מזגן"), s("heat-repair", "Heating-system repair", "תיקון מערכת חימום"),
    s("no-cool", "No-cooling service", "טיפול במערכת שאינה מקררת"), s("no-heat", "No-heat service", "טיפול במערכת שאינה מחממת"),
    s("coil-clean", "Condenser coil cleaning", "ניקוי סוללת מעבה"), s("drain", "Condensate drain clearing", "פתיחת ניקוז עיבוי"),
    s("thermostat", "Thermostat installation", "התקנת תרמוסטט"), s("refrigerant", "Refrigerant leak diagnosis", "אבחון דליפת גז קירור"),
    s("indoor-air", "Indoor-air-quality assessment", "בדיקת איכות אוויר בתוך הבית"), s("mini-split", "Mini-split service", "שירות למזגן מיני-ספליט"),
    s("replace", "System replacement estimate", "הצעת מחיר להחלפת מערכת"), s("install", "New HVAC system installation", "התקנת מערכת מיזוג חדשה"),
    p("capacitor", "Run capacitor", "קבל הפעלה"), p("contactor", "HVAC contactor", "קונטקטור למיזוג"), p("thermostat-part", "Smart thermostat", "תרמוסטט חכם"),
    p("filter-part", "Replacement air filter", "מסנן אוויר חלופי"), p("pump", "Condensate pump", "משאבת עיבוי"),
  ]},
  { key: "plumbing", en: "Plumbing", he: "אינסטלציה", items: [
    s("diagnostic", "Plumbing diagnostic visit", "ביקור אבחון אינסטלציה"), s("leak", "Water-leak repair", "תיקון נזילת מים"),
    s("faucet", "Faucet repair or replacement", "תיקון או החלפת ברז"), s("toilet", "Toilet repair", "תיקון אסלה"),
    s("toilet-install", "Toilet installation", "התקנת אסלה"), s("drain", "Drain clearing", "פתיחת סתימה"),
    s("sewer", "Main sewer-line clearing", "פתיחת קו ביוב ראשי"), s("camera", "Sewer camera inspection", "בדיקת קו ביוב במצלמה"),
    s("disposal", "Garbage-disposal service", "שירות לטוחן אשפה"), s("heater", "Water-heater repair", "תיקון דוד מים"),
    s("heater-install", "Water-heater installation", "התקנת דוד מים"), s("pressure", "Water-pressure diagnosis", "אבחון לחץ מים"),
    s("repipe", "Repiping consultation", "ייעוץ להחלפת צנרת"), s("emergency", "Emergency plumbing service", "שירות אינסטלציה דחוף"),
    p("faucet-part", "Faucet", "ברז"), p("toilet-part", "Toilet fill valve", "מצוף מילוי לאסלה"), p("disposal-part", "Garbage disposal", "טוחן אשפה"),
    p("heater-part", "Water heater", "דוד מים"), p("shutoff", "Water shutoff valve", "ברז ניתוק מים"),
  ]},
  { key: "electrical", en: "Electrical", he: "חשמל", items: [
    s("diagnostic", "Electrical diagnostic visit", "ביקור אבחון חשמל"), s("outlet", "Outlet repair or replacement", "תיקון או החלפת שקע"),
    s("gfci", "GFCI outlet installation", "התקנת שקע מוגן GFCI"), s("switch", "Light-switch replacement", "החלפת מתג תאורה"),
    s("fixture", "Light-fixture installation", "התקנת גוף תאורה"), s("fan", "Ceiling-fan installation", "התקנת מאוורר תקרה"),
    s("breaker", "Circuit-breaker replacement", "החלפת מפסק בלוח"), s("panel", "Electrical-panel service", "שירות ללוח חשמל"),
    s("dedicated", "Dedicated circuit installation", "התקנת קו חשמל ייעודי"), s("ev", "EV charger installation", "התקנת מטען לרכב חשמלי"),
    s("surge", "Whole-home surge protection", "הגנת נחשולי מתח לכל הבית"), s("smoke", "Smoke/CO detector installation", "התקנת גלאי עשן ופחמן חד-חמצני"),
    s("rewire", "Rewiring consultation", "ייעוץ לחיווט מחדש"), s("emergency", "Emergency electrical service", "שירות חשמל דחוף"),
    p("outlet-part", "Duplex outlet", "שקע כפול"), p("gfci-part", "GFCI outlet", "שקע מוגן GFCI"), p("breaker-part", "Circuit breaker", "מפסק ללוח חשמל"),
    p("surge-part", "Whole-home surge protector", "מגן נחשולים לכל הבית"), p("detector", "Smoke and CO detector", "גלאי עשן ופחמן חד-חמצני"),
  ]},
  { key: "cleaning", en: "Cleaning", he: "ניקיון", items: [
    s("standard", "Standard home cleaning", "ניקיון בית רגיל"), s("deep", "Deep cleaning", "ניקיון יסודי"),
    s("move-in", "Move-in cleaning", "ניקיון לפני כניסה"), s("move-out", "Move-out cleaning", "ניקיון לאחר פינוי"),
    s("recurring", "Recurring cleaning visit", "ביקור ניקיון קבוע"), s("office", "Office cleaning", "ניקיון משרד"),
    s("construction", "Post-construction cleaning", "ניקיון לאחר שיפוץ"), s("windows", "Interior window cleaning", "ניקוי חלונות פנימי"),
    s("appliance", "Appliance interior cleaning", "ניקוי פנימי של מכשירי חשמל"), s("cabinet", "Cabinet interior cleaning", "ניקוי פנימי של ארונות"),
    s("carpet", "Carpet spot treatment", "טיפול נקודתי בשטיח"), s("odor", "Odor treatment", "טיפול בריחות"),
    s("rental", "Short-term rental turnover", "ניקיון בין אורחים בנכס להשכרה קצרה"), s("emergency", "Same-day cleaning service", "שירות ניקיון מהיום להיום"),
    p("supply-kit", "General cleaning supply kit", "ערכת חומרי ניקוי כללית"), p("degreaser", "Kitchen degreaser", "מסיר שומנים למטבח"), p("glass", "Glass cleaner", "חומר לניקוי זכוכית"),
    p("disinfectant", "Disinfectant", "חומר חיטוי"), p("bags", "Waste bags and consumables", "שקיות אשפה וחומרים מתכלים"),
  ]},
];

export function catalogItemsFor(trades: string[], includeParts: boolean, locale: "en" | "he") {
  return INDUSTRY_PACKS.filter((pack) => trades.includes(pack.key)).flatMap((pack) =>
    pack.items.filter((item) => includeParts || item.kind === "service").map((item) => ({
      name: locale === "he" ? item.he : item.en,
      category: locale === "he" ? pack.he : pack.en,
      unit: locale === "he" ? "יחידה" : "each",
      price_minor: 0,
      cost_minor: 0,
      taxable: true,
      industry_key: pack.key,
      pack_item_key: `${pack.key}:${item.kind}:${item.key}`,
      item_kind: item.kind,
    })),
  );
}

