-- ServicePro operations, growth, migration and intelligence foundation.
-- Additive only: existing jobs, customers, documents and payment workflows remain intact.

alter table public.jobs add column if not exists end_date date;
update public.jobs set end_date = scheduled_date where end_date is null;

create table if not exists public.crews (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, color text not null default '#2463eb', active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, name)
);
create table if not exists public.crew_members (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  crew_id uuid not null references public.crews(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete cascade,
  is_lead boolean not null default false, created_at timestamptz not null default now(), unique (crew_id, profile_id)
);
create table if not exists public.job_assignments (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade, profile_id uuid references public.profiles(id) on delete cascade,
  crew_id uuid references public.crews(id) on delete cascade, is_lead boolean not null default false,
  assignment_status text not null default 'assigned' check (assignment_status in ('assigned','accepted','declined','completed')),
  created_at timestamptz not null default now(), check (profile_id is not null or crew_id is not null),
  unique (job_id, profile_id), unique (job_id, crew_id)
);
create unique index if not exists uq_job_assignment_profile on public.job_assignments(job_id, profile_id) where profile_id is not null;
create unique index if not exists uq_job_assignment_crew on public.job_assignments(job_id, crew_id) where crew_id is not null;
create index if not exists idx_job_assignments_profile on public.job_assignments(profile_id, job_id);

create table if not exists public.service_areas (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, area_type text not null default 'zip' check (area_type in ('zip','city','polygon')),
  values_json jsonb not null default '[]', active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.technician_location_consents (
  profile_id uuid primary key references public.profiles(id) on delete cascade, organization_id uuid not null references public.organizations(id) on delete cascade,
  consented boolean not null default false, consented_at timestamptz, revoked_at timestamptz, updated_at timestamptz not null default now()
);
create table if not exists public.technician_locations (
  id bigint generated by default as identity primary key, organization_id uuid not null references public.organizations(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade, latitude double precision not null, longitude double precision not null,
  accuracy_m double precision, recorded_at timestamptz not null default now()
);
create index if not exists idx_tech_location_latest on public.technician_locations(profile_id, recorded_at desc);

create table if not exists public.custom_field_definitions (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  entity_type text not null check (entity_type in ('customer','job')), label text not null,
  field_type text not null check (field_type in ('text','number','date','choice','checkbox')),
  options_json jsonb not null default '[]', required boolean not null default false, active boolean not null default true,
  sort integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.custom_field_values (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  definition_id uuid not null references public.custom_field_definitions(id) on delete cascade,
  entity_type text not null check (entity_type in ('customer','job')), entity_id uuid not null, value_json jsonb,
  updated_by uuid references public.profiles(id) on delete set null, updated_at timestamptz not null default now(),
  unique (definition_id, entity_id)
);

create table if not exists public.automation_rules (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, trigger_type text not null, condition_json jsonb not null default '{}', action_type text not null,
  action_json jsonb not null default '{}', enabled boolean not null default true, last_run_at timestamptz,
  created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.automation_runs (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  rule_id uuid not null references public.automation_rules(id) on delete cascade, source_type text, source_id uuid,
  status text not null default 'pending' check (status in ('pending','running','succeeded','failed','skipped')),
  error_message text, attempts integer not null default 0, created_at timestamptz not null default now(), finished_at timestamptz
);

create table if not exists public.vendors (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, contact_name text, email text, phone text, address text, notes text, active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.purchase_orders (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  po_number text not null, vendor_id uuid references public.vendors(id) on delete set null, job_id uuid references public.jobs(id) on delete set null,
  status text not null default 'draft' check (status in ('draft','ordered','partially_received','received','cancelled')),
  expected_date date, total_minor bigint not null default 0, notes text, created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (organization_id, po_number)
);
create table if not exists public.purchase_order_items (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade, description text not null,
  quantity numeric(12,3) not null default 1, unit_cost_minor bigint not null default 0, received_quantity numeric(12,3) not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.subcontractors (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  company_name text not null, contact_name text, email text, phone text, trades text[] not null default '{}',
  insurance_expires_on date, notes text, active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.subcontractor_assignments (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  subcontractor_id uuid not null references public.subcontractors(id) on delete cascade, job_id uuid not null references public.jobs(id) on delete cascade,
  scope text, agreed_cost_minor bigint not null default 0, status text not null default 'assigned', created_at timestamptz not null default now(),
  unique (subcontractor_id, job_id)
);

create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, channel text not null check (channel in ('email','sms','both')), audience_json jsonb not null default '{}',
  subject text, body text not null, status text not null default 'draft' check (status in ('draft','scheduled','sending','sent','paused')),
  scheduled_at timestamptz, sent_count integer not null default 0, created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.referral_programs (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null, reward_text text not null, active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.referrals (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  program_id uuid references public.referral_programs(id) on delete set null, referrer_customer_id uuid references public.customers(id) on delete set null,
  referred_customer_id uuid references public.customers(id) on delete set null, code text not null, status text not null default 'shared',
  reward_status text not null default 'pending', created_at timestamptz not null default now(), unique (organization_id, code)
);
create table if not exists public.estimate_followups (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  estimate_id uuid not null references public.estimates(id) on delete cascade, channel text not null check (channel in ('email','sms')),
  scheduled_at timestamptz not null, status text not null default 'scheduled' check (status in ('scheduled','sent','cancelled','failed')),
  created_at timestamptz not null default now()
);
create table if not exists public.lead_attribution_costs (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  source text not null, campaign text, period_start date not null, period_end date not null, spend_minor bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.migration_batches (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  source text not null check (source in ('workiz','housecall_pro','spreadsheet')), filename text,
  status text not null default 'uploaded' check (status in ('uploaded','mapped','validated','importing','completed','failed','rolled_back')),
  counts_json jsonb not null default '{}', errors_json jsonb not null default '[]', created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(), completed_at timestamptz
);
alter table public.customers add column if not exists migration_batch_id uuid references public.migration_batches(id) on delete set null;
alter table public.customers add column if not exists external_source text;
alter table public.customers add column if not exists external_id text;
alter table public.jobs add column if not exists migration_batch_id uuid references public.migration_batches(id) on delete set null;
alter table public.jobs add column if not exists external_source text;
alter table public.jobs add column if not exists external_id text;
alter table public.job_photos add column if not exists media_type text not null default 'image' check (media_type in ('image','video'));
alter table public.job_photos add column if not exists parent_photo_id uuid references public.job_photos(id) on delete set null;
alter table public.job_photos add column if not exists customer_visible boolean not null default true;
create unique index if not exists uq_customers_external_source on public.customers(organization_id, external_source, external_id);
create unique index if not exists uq_jobs_external_source on public.jobs(organization_id, external_source, external_id);
create table if not exists public.job_summary_drafts (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade, summary text not null, source_refs jsonb not null default '[]',
  provider text, model text, status text not null default 'draft' check (status in ('draft','approved','rejected')),
  created_by uuid references public.profiles(id) on delete set null, approved_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(), approved_at timestamptz
);
create table if not exists public.sync_outbox_receipts (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade, client_event_id uuid not null,
  job_id uuid not null references public.jobs(id) on delete cascade, action_type text not null,
  status text not null default 'processed' check (status in ('processed','rejected')),
  processed_at timestamptz not null default now(), unique (profile_id, client_event_id)
);
alter table public.customers add column if not exists email_opt_in boolean not null default true;
alter table public.customers add column if not exists sms_opt_in boolean not null default true;
create table if not exists public.customer_portal_requests (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade, job_id uuid references public.jobs(id) on delete set null,
  request_type text not null check (request_type in ('reschedule','question')),
  requested_date date, message text, status text not null default 'new' check (status in ('new','reviewing','approved','declined','closed')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

do $$
declare r record;
begin
  for r in select * from (values
    ('crew_members','crew_members_crew_org_guard','crews','crew_id'),('crew_members','crew_members_profile_org_guard','profiles','profile_id'),
    ('job_assignments','job_assignments_job_org_guard','jobs','job_id'),('job_assignments','job_assignments_profile_org_guard','profiles','profile_id'),('job_assignments','job_assignments_crew_org_guard','crews','crew_id'),
    ('technician_location_consents','location_consents_profile_org_guard','profiles','profile_id'),('technician_locations','technician_locations_profile_org_guard','profiles','profile_id'),
    ('custom_field_values','custom_values_definition_org_guard','custom_field_definitions','definition_id'),('automation_runs','automation_runs_rule_org_guard','automation_rules','rule_id'),
    ('purchase_orders','purchase_orders_vendor_org_guard','vendors','vendor_id'),('purchase_orders','purchase_orders_job_org_guard','jobs','job_id'),
    ('purchase_order_items','purchase_items_order_org_guard','purchase_orders','purchase_order_id'),
    ('subcontractor_assignments','sub_assignments_sub_org_guard','subcontractors','subcontractor_id'),('subcontractor_assignments','sub_assignments_job_org_guard','jobs','job_id'),
    ('referrals','referrals_program_org_guard','referral_programs','program_id'),('referrals','referrals_from_customer_org_guard','customers','referrer_customer_id'),('referrals','referrals_to_customer_org_guard','customers','referred_customer_id'),
    ('estimate_followups','estimate_followups_estimate_org_guard','estimates','estimate_id'),('job_summary_drafts','job_summary_job_org_guard','jobs','job_id'),
    ('sync_outbox_receipts','sync_receipts_profile_org_guard','profiles','profile_id'),('sync_outbox_receipts','sync_receipts_job_org_guard','jobs','job_id'),
    ('customer_portal_requests','portal_requests_customer_org_guard','customers','customer_id'),('customer_portal_requests','portal_requests_job_org_guard','jobs','job_id')
  ) as t(tbl,trg,parent,fkcol) loop
    execute format('drop trigger if exists %I on public.%I;',r.trg,r.tbl);
    execute format('create trigger %I before insert or update on public.%I for each row execute function public.assert_child_org(%L,%L);',r.trg,r.tbl,r.parent,r.fkcol);
  end loop;
end $$;

do $$
declare t text;
begin
  foreach t in array array['crews','service_areas','technician_location_consents','custom_field_definitions','custom_field_values','automation_rules','vendors','purchase_orders','subcontractors','campaigns','referral_programs','customer_portal_requests'] loop
    execute format('drop trigger if exists trg_%s_updated on public.%I;', t, t);
    execute format('create trigger trg_%s_updated before update on public.%I for each row execute function public.set_updated_at();', t, t);
  end loop;
end $$;

do $$
declare t text;
begin
  foreach t in array array[
    'crews','crew_members','job_assignments','service_areas','technician_location_consents','technician_locations',
    'custom_field_definitions','custom_field_values','automation_rules','automation_runs','vendors','purchase_orders',
    'purchase_order_items','subcontractors','subcontractor_assignments','campaigns','referral_programs','referrals',
    'estimate_followups','lead_attribution_costs','migration_batches','job_summary_drafts','sync_outbox_receipts','customer_portal_requests'
  ] loop
    execute format('alter table public.%I enable row level security;', t);
    execute format('drop policy if exists %I on public.%I;', t || '_select', t);
    execute format('create policy %I on public.%I for select to authenticated using (organization_id = public.current_org_id());', t || '_select', t);
    execute format('drop policy if exists %I on public.%I;', t || '_manage', t);
    execute format('create policy %I on public.%I for all to authenticated using (organization_id = public.current_org_id() and public.current_user_role() in (''owner'',''office'')) with check (organization_id = public.current_org_id() and public.current_user_role() in (''owner'',''office''));', t || '_manage', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated;', t);
    execute format('grant all on public.%I to service_role;', t);
    execute format('revoke all on public.%I from anon;', t);
  end loop;
end $$;

-- Technicians can record only their own location after explicit consent.
drop policy if exists technician_locations_own_insert on public.technician_locations;
create policy technician_locations_own_insert on public.technician_locations for insert to authenticated
  with check (organization_id = public.current_org_id() and profile_id = auth.uid() and exists (
    select 1 from public.technician_location_consents c where c.profile_id = auth.uid() and c.consented
  ));
drop policy if exists technician_consent_own on public.technician_location_consents;
create policy technician_consent_own on public.technician_location_consents for all to authenticated
  using (organization_id = public.current_org_id() and profile_id = auth.uid())
  with check (organization_id = public.current_org_id() and profile_id = auth.uid());

drop policy if exists job_summary_drafts_assigned_tech on public.job_summary_drafts;
create policy job_summary_drafts_assigned_tech on public.job_summary_drafts for all to authenticated
  using (organization_id = public.current_org_id() and exists (select 1 from public.jobs j where j.id = job_id and j.assigned_to = auth.uid()))
  with check (organization_id = public.current_org_id() and exists (select 1 from public.jobs j where j.id = job_id and j.assigned_to = auth.uid()));

drop policy if exists sync_outbox_receipts_own on public.sync_outbox_receipts;
create policy sync_outbox_receipts_own on public.sync_outbox_receipts for select to authenticated
  using (organization_id = public.current_org_id() and profile_id = auth.uid());
drop policy if exists sync_outbox_receipts_own_insert on public.sync_outbox_receipts;
create policy sync_outbox_receipts_own_insert on public.sync_outbox_receipts for insert to authenticated
  with check (organization_id = public.current_org_id() and profile_id = auth.uid());

grant usage, select on sequence public.technician_locations_id_seq to authenticated, service_role;

create or replace function public.public_customer_portal(p_token uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare cust record; org record; ests jsonb; invs jsonb; jbs jsonb;
begin
  select * into cust from public.customers where portal_token = p_token and deleted_at is null;
  if not found then return null; end if;
  select name, tagline, logo_url, accent_color, phone, email, currency, locale into org from public.organizations where id = cust.organization_id;
  select coalesce(jsonb_agg(jsonb_build_object('number', number, 'status', status, 'total_minor', total_minor, 'issue_date', issue_date, 'token', public_token) order by number desc), '[]'::jsonb) into ests from public.estimates where customer_id = cust.id and deleted_at is null;
  select coalesce(jsonb_agg(jsonb_build_object('number', number, 'status', status, 'total_minor', total_minor, 'issue_date', issue_date, 'token', public_token) order by number desc), '[]'::jsonb) into invs from public.invoices where customer_id = cust.id and deleted_at is null;
  select coalesce(jsonb_agg(jsonb_build_object('id', id, 'service', service, 'status', status, 'date', scheduled_date, 'end_date', end_date, 'start_time', start_time, 'address', job_address, 'city', job_city) order by scheduled_date desc), '[]'::jsonb) into jbs from public.jobs where customer_id = cust.id and deleted_at is null;
  return jsonb_build_object('customer', jsonb_build_object('name', cust.name, 'phone', cust.phone, 'email', cust.email, 'email_opt_in', cust.email_opt_in, 'sms_opt_in', cust.sms_opt_in), 'org', jsonb_build_object('name', org.name, 'tagline', org.tagline, 'logo_url', org.logo_url, 'accent_color', org.accent_color, 'phone', org.phone, 'email', org.email, 'currency', org.currency, 'locale', org.locale), 'estimates', ests, 'invoices', invs, 'jobs', jbs);
end $$;
revoke all on function public.public_customer_portal(uuid) from public;
grant execute on function public.public_customer_portal(uuid) to anon, authenticated, service_role;

create or replace function public.submit_customer_portal_request(p_token uuid, p_type text, p_job uuid default null, p_date date default null, p_message text default null, p_email_opt_in boolean default null, p_sms_opt_in boolean default null)
returns boolean language plpgsql security definer set search_path = '' as $$
declare cust public.customers; recent_count integer;
begin
  select * into cust from public.customers where portal_token = p_token and deleted_at is null;
  if not found then return false; end if;
  if p_type = 'preferences' then update public.customers set email_opt_in = coalesce(p_email_opt_in,email_opt_in), sms_opt_in = coalesce(p_sms_opt_in,sms_opt_in) where id = cust.id; return true; end if;
  if p_type not in ('reschedule','question') then return false; end if;
  select count(*) into recent_count from public.customer_portal_requests where customer_id = cust.id and created_at > now() - interval '1 hour';
  if recent_count >= 10 then return false; end if;
  if p_job is not null and not exists (select 1 from public.jobs where id = p_job and customer_id = cust.id) then return false; end if;
  insert into public.customer_portal_requests(organization_id,customer_id,job_id,request_type,requested_date,message) values(cust.organization_id,cust.id,p_job,p_type,p_date,left(nullif(trim(p_message),''),2000));
  return true;
end $$;
revoke all on function public.submit_customer_portal_request(uuid,text,uuid,date,text,boolean,boolean) from public;
grant execute on function public.submit_customer_portal_request(uuid,text,uuid,date,text,boolean,boolean) to anon, authenticated, service_role;
