import { redirect } from "next/navigation";
import { requireProfile } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { getLocale } from "@/lib/locale-server";
import PrivacyCenter from "./PrivacyCenter";

export const dynamic="force-dynamic";
export default async function PrivacyPage(){const profile=await requireProfile();if(profile.role!=="owner")redirect(profile.role==="tech"?"/tech":"/dispatch");const locale=await getLocale(),he=locale==="he",supabase=await createClient();const[{data:settings},{data:customers},{data:members},{data:consents},{data:requests},{data:holds},{data:runs}]=await Promise.all([supabase.from("organization_privacy_settings").select("*").eq("organization_id",profile.organization_id!).single(),supabase.from("customers").select("id,name,email,phone").is("deleted_at",null).order("name"),supabase.from("profiles").select("id,full_name").eq("active",true).order("full_name"),supabase.from("consent_events").select("id,channel,purpose,granted,source,recorded_at,customers(name)").order("recorded_at",{ascending:false}).limit(250),supabase.from("privacy_requests").select("id,request_type,status,requester_name,requester_email,received_at,due_at,identity_verified_at,completion_notes,customer_id,customers(name)").order("received_at",{ascending:false}),supabase.from("retention_holds").select("id,category,reason,expires_at,released_at,customers(name)").order("created_at",{ascending:false}),supabase.from("retention_runs").select("id,mode,status,summary,started_at").order("started_at",{ascending:false}).limit(10)]);const defaults={privacy_email:null,privacy_phone:null,location_retention_days:30,call_recording_retention_days:90,communication_retention_days:730,job_media_retention_days:2555,audit_retention_days:2555,auto_enforce:false};return <div className="ops-page"><header className="ops-heading"><div><span>{he?"אמון ושליטה":"Trust & control"}</span><h1>{he?"פרטיות ושמירת מידע":"Privacy & data retention"}</h1><p>{he?"מנהלים הסכמות, בקשות לקוחות ומחיקה אחראית בלי לפגוע במסמכים שחייבים לשמור.":"Manage consent, customer requests and responsible deletion without losing records that must be retained."}</p></div><div className="ops-heading-mark" aria-hidden="true">✓</div></header><PrivacyCenter locale={locale} settings={(settings??defaults) as any} customers={customers??[]} members={members??[]} consents={(consents??[]) as any} requests={(requests??[]) as any} holds={(holds??[]) as any} runs={(runs??[]) as any}/></div>}

