import { redirect } from "next/navigation";
import { requireProfile } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { getLocale } from "@/lib/locale-server";
import { createAutomation, createCrew, createPurchaseOrder, createServiceArea, createSubcontractor, createVendor } from "./actions";
import ActionForm from "@/components/ActionForm";

export const dynamic = "force-dynamic";

export default async function OperationsPage() {
  const profile = await requireProfile(); if (profile.role === "tech") redirect("/tech");
  const locale = await getLocale(); const he = locale === "he"; const supabase = await createClient();
  const [{ data: crews }, { data: areas }, { data: rules }, { data: vendors }, { data: orders }, { data: subcontractors }, { data: jobs }, { data: org }] = await Promise.all([
    supabase.from("crews").select("id,name,color,active").order("name"),
    supabase.from("service_areas").select("id,name,area_type,values_json,active").order("name"),
    supabase.from("automation_rules").select("id,name,trigger_type,action_type,enabled").order("created_at", { ascending: false }),
    supabase.from("vendors").select("id,name,contact_name,email,phone").eq("active", true).order("name"),
    supabase.from("purchase_orders").select("id,po_number,status,total_minor,vendors(name)").order("created_at", { ascending: false }).limit(20),
    supabase.from("subcontractors").select("id,company_name,contact_name,trades,insurance_expires_on").eq("active", true).order("company_name"),
    supabase.from("jobs").select("id,service,customers(name)").is("deleted_at", null).order("scheduled_date", { ascending: false }).limit(50),
    supabase.from("organizations").select("currency").single(),
  ]);
  const money = (minor: number) => new Intl.NumberFormat(he ? "he-IL" : "en-US", { style: "currency", currency: org?.currency ?? "USD" }).format(minor / 100);
  const saved = he ? "נשמר" : "Saved";
  return <div className="ops-page">
    <header className="ops-hero"><span>{he ? "תפעול" : "Operations"}</span><h1>{he ? "כל מה שמחזיק את העבודה בתנועה" : "Keep every job moving"}</h1><p>{he ? "צוותים, אזורי שירות, אוטומציות, ספקים, הזמנות רכש וקבלני משנה — במקום אחד." : "Crews, service areas, automations, vendors, purchase orders and subcontractors in one place."}</p></header>
    <div className="ops-grid">
      <OpsSection title={he ? "צוותים" : "Crews"} count={crews?.length ?? 0}><ActionForm action={createCrew} className="ops-inline-form" successLabel={saved}><input name="name" required placeholder={he ? "שם הצוות" : "Crew name"} /><input name="color" type="color" defaultValue="#2463eb" /><button>{he ? "הוספה" : "Add"}</button></ActionForm><div className="ops-list">{(crews ?? []).map((row) => <div key={row.id}><i style={{ background: row.color }} /><strong>{row.name}</strong><small>{row.active ? (he ? "פעיל" : "Active") : (he ? "מושהה" : "Paused")}</small></div>)}</div></OpsSection>
      <OpsSection title={he ? "אזורי שירות" : "Service areas"} count={areas?.length ?? 0}><ActionForm action={createServiceArea} className="ops-form" successLabel={saved}><input name="name" required placeholder={he ? "למשל: צפון אוסטין" : "e.g. North Austin"} /><div className="ops-form-row"><select name="areaType"><option value="zip">ZIP</option><option value="city">{he ? "עיר" : "City"}</option></select><input name="values" required placeholder={he ? "78701, 78702" : "78701, 78702"} /></div><button>{he ? "שמירת אזור" : "Save area"}</button></ActionForm><div className="ops-list">{(areas ?? []).map((row) => <div key={row.id}><strong>{row.name}</strong><small>{row.area_type.toUpperCase()} · {Array.isArray(row.values_json) ? row.values_json.join(", ") : ""}</small></div>)}</div></OpsSection>
      <OpsSection title={he ? "אוטומציות" : "Automations"} count={rules?.length ?? 0}><ActionForm action={createAutomation} className="ops-form" successLabel={saved}><input name="name" required placeholder={he ? "שם האוטומציה" : "Automation name"} /><div className="ops-form-row"><select name="triggerType"><option value="job_completed">{he ? "כשעבודה הושלמה" : "When a job is completed"}</option><option value="estimate_sent">{he ? "כשהצעה נשלחה" : "When an estimate is sent"}</option><option value="invoice_overdue">{he ? "כשחשבונית באיחור" : "When an invoice is overdue"}</option></select><select name="actionType"><option value="send_sms">{he ? "שליחת SMS" : "Send SMS"}</option><option value="send_email">{he ? "שליחת אימייל" : "Send email"}</option><option value="create_task">{he ? "יצירת משימה" : "Create task"}</option></select></div><textarea name="message" placeholder={he ? "מה תרצו שיקרה?" : "What should happen?"} /><button>{he ? "יצירת אוטומציה" : "Create automation"}</button></ActionForm><div className="ops-list">{(rules ?? []).map((row) => <div key={row.id}><strong>{row.name}</strong><small>{row.trigger_type.replaceAll("_", " ")} → {row.action_type.replaceAll("_", " ")}</small><b>{row.enabled ? (he ? "פעילה" : "On") : (he ? "כבויה" : "Off")}</b></div>)}</div></OpsSection>
      <OpsSection title={he ? "ספקים" : "Vendors"} count={vendors?.length ?? 0}><ActionForm action={createVendor} className="ops-form" successLabel={saved}><input name="name" required placeholder={he ? "שם הספק" : "Vendor name"} /><div className="ops-form-row"><input name="contactName" placeholder={he ? "איש קשר" : "Contact"} /><input name="phone" placeholder={he ? "טלפון" : "Phone"} /></div><input name="email" type="email" placeholder={he ? "אימייל" : "Email"} /><button>{he ? "הוספת ספק" : "Add vendor"}</button></ActionForm><div className="ops-list">{(vendors ?? []).map((row) => <div key={row.id}><strong>{row.name}</strong><small>{[row.contact_name,row.phone,row.email].filter(Boolean).join(" · ")}</small></div>)}</div></OpsSection>
      <OpsSection title={he ? "הזמנות רכש" : "Purchase orders"} count={orders?.length ?? 0}><ActionForm action={createPurchaseOrder} className="ops-form" successLabel={saved}><div className="ops-form-row"><select name="vendorId"><option value="">{he ? "בחירת ספק" : "Choose vendor"}</option>{(vendors ?? []).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><select name="jobId"><option value="">{he ? "ללא עבודה" : "No job"}</option>{(jobs ?? []).map((row) => <option key={row.id} value={row.id}>{row.service}</option>)}</select></div><input name="description" required placeholder={he ? "פריט או חומר" : "Item or material"} /><div className="ops-form-row"><input name="quantity" type="number" min="0.001" step="0.001" defaultValue="1" /><input name="unitCost" type="number" min="0" step="0.01" placeholder={he ? "עלות ליחידה" : "Unit cost"} /></div><button>{he ? "יצירת הזמנה" : "Create PO"}</button></ActionForm><div className="ops-list">{(orders ?? []).map((row) => <div key={row.id}><strong>{row.po_number} · {(row.vendors as { name: string }[] | null)?.[0]?.name}</strong><small>{row.status.replaceAll("_", " ")}</small><b>{money(row.total_minor)}</b></div>)}</div></OpsSection>
      <OpsSection title={he ? "קבלני משנה" : "Subcontractors"} count={subcontractors?.length ?? 0}><ActionForm action={createSubcontractor} className="ops-form" successLabel={saved}><input name="companyName" required placeholder={he ? "שם החברה" : "Company name"} /><div className="ops-form-row"><input name="contactName" placeholder={he ? "איש קשר" : "Contact"} /><input name="phone" placeholder={he ? "טלפון" : "Phone"} /></div><input name="email" type="email" placeholder={he ? "אימייל" : "Email"} /><div className="ops-form-row"><input name="trades" placeholder={he ? "תחומים, מופרדים בפסיק" : "Trades, comma separated"} /><input name="insuranceExpires" type="date" title={he ? "תוקף ביטוח" : "Insurance expiry"} /></div><button>{he ? "הוספת קבלן" : "Add subcontractor"}</button></ActionForm><div className="ops-list">{(subcontractors ?? []).map((row) => <div key={row.id}><strong>{row.company_name}</strong><small>{[row.contact_name,...(row.trades ?? [])].filter(Boolean).join(" · ")}</small>{row.insurance_expires_on && <b>{he ? "ביטוח עד" : "Insured to"} {row.insurance_expires_on}</b>}</div>)}</div></OpsSection>
    </div>
  </div>;
}

function OpsSection({ title, count, children }: { title: string; count: number; children: React.ReactNode }) {
  return <section className="ops-card"><header><h2>{title}</h2><b>{count}</b></header>{children}</section>;
}
